config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  root "home#index"

  resources :sections
  resources :race_reports

  get "/dashboard", to: "dashboard#index", as: :dashboard
  get "/:id", to: "profile#index", as: :profile
  get "/:id/:race_id", to: "profile#show", as: :race_report_profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/race_report.rb
class RaceReport < ApplicationRecord
  extend FriendlyId

  belongs_to :user
  has_many :sections, dependent: :destroy

  accepts_nested_attributes_for :sections, allow_destroy: true

  friendly_id :slug_candidates, use: :slugged

  enum status: {
    active: 1,
    deleted: 2
  }

  store_accessor :goals,
    :goal_a, :goal_a_completed,
    :goal_b, :goal_b_completed,
    :goal_c, :goal_c_completed

  validates :user, presence: true
  validates :name, presence: true
  validates :race_date, presence: true
  validates :status, presence: true

  after_initialize :set_default_values, if: :new_record?

  private

  def slug_candidates
    [
      [:user_id, :name, :race_date]
    ]
  end

  def set_default_values
    self.status ||= :active
  end
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :race_report, optional: true

  validates :title, presence: true
  validates :description, presence: true
  validates :order, presence: true, numericality: true

  default_scope { order(order: :asc) }
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :lockable

  friendly_id :username

  has_many :race_reports, dependent: :destroy

  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true, uniqueness: { case_sensitive: false },
    format: { with: /\A[a-z0-9]+\z/ }, length: { minimum: 1, maximum: 30 }

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  helper_method :user, :owner?

  def index
    @race_reports = user.race_reports.active
  end

  def show
    @race_report = RaceReport.active.includes(:user, :sections).friendly.find(params[:race_id])
  end

  private

  def user
    @user ||= User.friendly.find(params[:id])
  end

  def owner?
    user_signed_in? && current_user.id == user&.id
  end
end

app/controllers/race_reports_controller.rb
class RaceReportsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_race_report, only: [:show, :edit, :update, :destroy]

  def index
    @race_reports = current_user.race_reports.all
  end

  def show
  end

  def new
    @race_report = RaceReport.new
    @race_report.sections.build
  end

  def edit
    @race_report.sections.build unless @race_report.sections.any?
  end

  def create
    @race_report = current_user.race_reports.new(race_report_params)

    respond_to do |format|
      if @race_report.save
        format.html { redirect_to @race_report, notice: 'Race report was successfully created.' }
        format.json { render :show, status: :created, location: @race_report }
      else
        format.html { render :new }
        format.json { render json: @race_report.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @race_report.update(race_report_params)
        format.html { redirect_to @race_report, notice: 'Race report was successfully updated.' }
        format.json { render :show, status: :ok, location: @race_report }
      else
        format.html { render :edit }
        format.json { render json: @race_report.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @race_report.destroy

    respond_to do |format|
      format.html { redirect_to race_reports_url, notice: 'Race report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_race_report
    @race_report = current_user.race_reports.friendly.find(params[:id])
  end

  def race_report_params
    params.require(:race_report).permit(:name, :distance, :location, :race_date, :website, :goal_a, :goal_a_completed, :goal_b, :goal_b_completed, :goal_c, :goal_c_completed,
      sections_attributes: [:id, :title, :description, :order, :_destroy]
    )
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])
  end

  def after_sign_up_path_for(resource)
    dashboard_path
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  protected

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || dashboard_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<h1><%= current_user.full_name %>!</h1>

<%= link_to "Edit Profile", "#" %>
<%= link_to "Add Race Report", new_race_report_path %>

<%= render "shared/authentication_links" %>

app/views/home/index.html.erb
<h1>Welcome to MyRace.Report</h1>

<%= render "shared/authentication_links" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Bandit</title>
    <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">My Race Report</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Profile", profile_path(current_user), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "custom-alert-#{key}") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/race_reports/_form.html.erb
<%= form_for(race_report) do |f| %>
  <% if race_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(race_report.errors.count, "error") %> prohibited this race_report from being saved:</h2>

      <ul>
      <% race_report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :distance %>
    <%= f.text_field :distance %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :goal_a %>
    <%= f.text_field :goal_a %>
    <%= f.check_box :goal_a_completed %>
  </div>

  <div class="field">
    <%= f.label :goal_b %>
    <%= f.text_field :goal_b %>
    <%= f.check_box :goal_b_completed %>
  </div>

  <div class="field">
    <%= f.label :goal_c %>
    <%= f.text_field :goal_c %>
    <%= f.check_box :goal_c_completed %>
  </div>

  <div class="field">
    <%= f.label :race_date %>
    <%= f.date_select :race_date %>
  </div>

  <div class="field">
    <%= f.label :website %>
    <%= f.text_field :website %>
  </div>

  <div id="race-report-sections">
    <%= f.fields_for :sections do |ff| %>
      <div class="section-item">
        <%= ff.hidden_field :id %>
        <%= ff.hidden_field :order %>
        <%= ff.hidden_field :_destroy %>

        <div class="field">
          <%= ff.label :title %>
          <%= ff.text_field :title, required: true, list: "names" %>
        </div>

        <div class="field">
          <%= ff.label :description %>
          <%= ff.text_area :description, required: true %>
        </div>

        <div class="actions">
          <span class="section-item-remove">✖</span>
          <span class="section-item-handle">☰</span>
        </div>
      </div>
    <% end %>
  </div>


  <p>
    <a href="#" id="addNewSection">Add new section</a>
  </p>

  <div class="actions">
    <%= f.submit %>
  </div>

  <datalist id="names">
    <option value="Pre race">
    <option value="Training">
    <option value="Equipment">
    <option value="Race day">
  </datalist>

<% end %>

app/views/race_reports/_section_form.html.erb
<div class="race-report-section">
  <%= hidden_field_tag :id %>

  <div class="field">
    <%= label_tag :title %>
    <%= text_field_tag :title %>
  </div>

  <div class="field">
    <%= label_tag :description %>
    <%= text_area_tag :description %>
  </div>

  <div class="field">
    <%= label_tag :order %>
    <%= text_area_tag :order %>
  </div>
</div>

app/views/race_reports/edit.html.erb
<h1>Editing Race Report</h1>

<%= render 'form', race_report: @race_report %>

<%= link_to 'Show', @race_report %> |
<%= link_to 'Back', race_reports_path %>

app/views/race_reports/index.html.erb
<h1>Race Reports</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Distance</th>
      <th>Location</th>
      <th>Race date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @race_reports.each do |race_report| %>
      <tr>
        <td><%= race_report.name %></td>
        <td><%= race_report.distance %></td>
        <td><%= race_report.location %></td>
        <td><%= race_report.race_date %></td>
        <td><%= link_to 'Show', race_report %></td>
        <td><%= link_to 'Edit', edit_race_report_path(race_report) %></td>
        <td><%= link_to 'Destroy', race_report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Race Report', new_race_report_path %>

app/views/race_reports/new.html.erb
<h1>New Race Report</h1>

<%= render 'form', race_report: @race_report %>

<%= link_to 'Back', race_reports_path %>

app/views/race_reports/show.html.erb
<p>
  <h1>Race Report: <%= @race_report.name %></h1>
</p>

<p>
  <strong>Distance:</strong>
  <%= @race_report.distance %>
</p>

<p>
  <strong>Location:</strong>
  <%= @race_report.location %>
</p>

<p>
  <strong>Race date:</strong>
  <%= @race_report.race_date %>
</p>

<% if @race_report.website.present? %>
<p>
  <strong>Website:</strong>
  <%= @race_report.website %>
</p>
<% end %>

<p>
  <table id="race-report-goals">
    <tr>
      <th>Goal</th>
      <th>Achieved?</th>
    </tr>
    <% if @race_report.goal_a.present? %>
      <% goal_achieved = @race_report.goal_a_completed == "1" %>
      <tr>
        <td><%= @race_report.goal_a %></td>
        <td class="<%= goal_achieved ? "achieved" : "not_achieved" %>"><%= goal_achieved ? "Yes" : "No" %></td>
      </tr>
    <% end %>
    <% if @race_report.goal_b.present? %>
      <% goal_achieved = @race_report.goal_b_completed == "1" %>
      <tr>
        <td><%= @race_report.goal_b %></td>
        <td class="<%= goal_achieved ? "achieved" : "not_achieved" %>"><%= goal_achieved ? "Yes" : "No" %></td>
      </tr>
    <% end %>
    <% if @race_report.goal_c.present? %>
      <% goal_achieved = @race_report.goal_c_completed == "1" %>
      <tr>
        <td><%= @race_report.goal_c %></td>
        <td class="<%= goal_achieved ? "achieved" : "not_achieved" %>"><%= goal_achieved ? "Yes" : "No" %></td>
      </tr>
    <% end %>
  </table>
</p>

<% @race_report.sections.each do |section| %>
  <div>
    <h2><%= section.title %></h2>
    <p><%= section.description %></p>
  </div>
<% end %>

<%= link_to 'Edit', edit_race_report_path(@race_report) %> |
<%= link_to 'Back', race_reports_path %>

app/views/shared/_authentication_links.html.erb
<% if user_signed_in? %>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign in", new_user_session_path %>
  <%= link_to "Sign up", new_user_registration_path %>
<% end %>